import type { PortfolioContentHubContent } from '../models/content-hub-content.model';

export const EN_CONTENT_HUB_CONTENT = {
  metaTitle: 'Content',
  metaDescription:
    'Explore articles and resources by Gonzalo Herrera about Angular, frontend engineering, technical leadership and AI-augmented development.',
  hero: {
    eyebrow: 'Content',
    title: 'Ideas, lessons and practical resources for building better software.',
    description:
      'Articles and resources about Angular, frontend engineering, technical leadership and AI-augmented development.',
    visualLabel: 'Content focus areas',
    visualTitle: 'Explore practical engineering knowledge',
    topics: ['Angular', 'Frontend Engineering', 'Technical Leadership', 'AI Engineering'],
  },
  featured: {
    eyebrow: 'Selected insight',
    title: 'Featured content',
    description:
      'A practical starting point for using AI in engineering while keeping human judgment in the loop.',
    linkLabel: 'Read the guide',
  },
  filters: {
    eyebrow: 'Explore by topic',
    title: 'Find the ideas most relevant to your work',
    description: 'Filter the published collection by its primary engineering topic.',
    label: 'Filter content by topic',
    options: [
      { id: 'all', label: 'All' },
      { id: 'angular', label: 'Angular' },
      { id: 'technical-leadership', label: 'Technical Leadership' },
      { id: 'ai-engineering', label: 'AI Engineering' },
    ],
  },
  grid: {
    eyebrow: 'Published collection',
    title: 'Articles and practical guides',
    description:
      'A deliberately focused collection grounded in the engineering and leadership practices documented in this repository.',
    cardLabels: {
      article: 'Content',
      featured: 'Featured',
      topics: 'Topics',
      read: 'Read content',
      viewExternal: 'View original publication',
      externalLink: 'opens in a new tab',
    },
  },
  empty: {
    title: 'No content found',
    description: 'There are no published items in this category yet.',
    resetLabel: 'View all content',
  },
  detail: {
    backToContent: 'Back to content',
    introduction: 'Introduction',
    metadataLabel: 'Publication details',
    publishedAt: 'Published',
    readingTime: 'Reading time',
    tags: 'Content topics',
    codeLanguage: 'Language',
    comparisonAspect: 'Area',
    relatedEyebrow: 'Continue exploring',
    relatedTitle: 'Related content',
    relatedDescription: 'More practical ideas connected by topic or engineering focus.',
    notFoundEyebrow: 'Content',
    notFoundTitle: 'Content not found',
    notFoundDescription:
      'The article or resource you are looking for does not exist or is not available.',
    notFoundMetaTitle: 'Content not found',
    notFoundMetaDescription: 'The requested portfolio content could not be found.',
  },
  contact: {
    eyebrow: 'Continue the conversation',
    title: 'Interested in discussing these ideas?',
    description:
      'If you are working on Angular architecture, frontend engineering or AI-assisted development, let’s connect.',
    actions: [
      { label: 'Get in touch', pageId: 'contact', variant: 'primary' },
      { label: 'View projects', pageId: 'projects', variant: 'secondary' },
    ],
  },
  typeLabels: {
    article: 'Article',
    project: 'Case study',
    linkedin: 'LinkedIn',
    resource: 'Guide',
    talk: 'Talk',
  },
  items: [
    {
      id: 'angular-14-vs-angular-20',
      slug: 'angular-14-vs-angular-20',
      title: 'Angular 14 vs Angular 20: an architecture review',
      excerpt:
        'A practical migration perspective on moving from module-heavy Angular applications toward standalone, signal-driven and SSR-ready architecture.',
      type: 'article',
      typeLabel: 'Article',
      category: 'angular',
      categoryLabel: 'Angular',
      status: 'published',
      statusLabel: 'Published',
      tags: ['Angular', 'Standalone Components', 'Signals', 'SSR'],
      featured: false,
      order: 1,
      source: { type: 'internal' },
      detailAvailable: true,
    },
    {
      id: 'lessons-from-code-reviews',
      slug: 'lessons-from-code-reviews',
      title: 'Lessons from thoughtful code reviews',
      excerpt:
        'Practical principles for making pull-request feedback clearer, more respectful and more useful to the whole engineering team.',
      type: 'article',
      typeLabel: 'Article',
      category: 'technical-leadership',
      categoryLabel: 'Technical Leadership',
      status: 'published',
      statusLabel: 'Published',
      tags: ['Code Review', 'Technical Leadership', 'Maintainability', 'Mentoring'],
      featured: false,
      order: 2,
      source: { type: 'internal' },
      detailAvailable: true,
    },
    {
      id: 'building-ai-agents',
      slug: 'building-ai-agents',
      title: 'Beyond chat: building AI agents that do real work',
      excerpt:
        'A practical guide to turning AI assistance into bounded engineering workflows while keeping technical judgment and human review explicit.',
      type: 'guide',
      typeLabel: 'Guide',
      category: 'ai-engineering',
      categoryLabel: 'AI Engineering',
      status: 'published',
      statusLabel: 'Published',
      tags: ['AI Agents', 'Engineering Workflows', 'Technical Judgment'],
      featured: true,
      order: 3,
      source: { type: 'internal' },
      detailAvailable: true,
    },
    {
      id: 'signals-forms-vs-reactive-forms',
      slug: 'signals-forms-vs-reactive-forms',
      title: 'Signal Forms vs Reactive Forms',
      excerpt:
        'A future comparison that will be published only after complete, verified bilingual content is available.',
      type: 'article',
      typeLabel: 'Article',
      category: 'angular',
      categoryLabel: 'Angular',
      status: 'planned',
      statusLabel: 'Planned',
      tags: ['Angular', 'Forms'],
      featured: false,
      order: 4,
      source: { type: 'internal' },
      detailAvailable: false,
    },
  ],
} as const satisfies PortfolioContentHubContent;
